version: "3"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - dbvolume:/var/log
    links:
      - mongo
    depends_on:
      - "mongo-express"
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - dbvolume:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "4778:8081"
    depends_on:
      - "mongo"
volumes:
  dbvolume: {}
